# Generated by Django 4.2.4 on 2024-06-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                (
                    "m2_construidos",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("m2_totales", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad_estacionamientos", models.IntegerField()),
                ("cantidad_habitaciones", models.IntegerField()),
                ("cantidad_banos", models.IntegerField()),
                ("direccion", models.CharField(max_length=255)),
                ("comuna", models.CharField(max_length=100)),
                ("tipo_inmueble", models.CharField(max_length=100)),
            ],
        ),
    ]
