# Generated by Django 4.2.4 on 2024-06-27 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_inmueble"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arrendador",
            fields=[
                (
                    "rut",
                    models.CharField(
                        default="11111111-1",
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("numero", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tipo_inmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Tipo_usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="inmueble",
            name="m2_totales",
        ),
        migrations.RemoveField(
            model_name="user",
            name="arrendador",
        ),
        migrations.AddField(
            model_name="inmueble",
            name="arrendada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inmueble",
            name="arrendatario",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.user"
            ),
        ),
        migrations.AddField(
            model_name="inmueble",
            name="m2_terreno",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="cantidad_estacionamientos",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="direccion",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="m2_construidos",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="Comuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                (
                    "region",
                    models.ForeignKey(
                        max_length=30,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.region",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inmueble",
            name="arrendador",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.arrendador",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="tipo_usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tipo_usuario",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="comuna",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.comuna"
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="tipo_inmueble",
            field=models.ForeignKey(
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tipo_inmueble",
            ),
        ),
    ]
