# Generated by Django 4.2.4 on 2024-06-28 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_arrendador_region_tipo_inmueble_tipo_usuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="arrendador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.arrendador",
            ),
        ),
    ]
