# Generated by Django 4.2.4 on 2024-06-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_inmueble_arrendador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="arrendador",
            field=models.ForeignKey(
                default=11111111,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.arrendador",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="arrendatario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.user",
            ),
        ),
    ]
