# Generated by Django 4.2.4 on 2024-07-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_inmueble_arrendador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arrendador",
            name="user",
            field=models.OneToOneField(
                default=111111111,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.user",
            ),
            preserve_default=False,
        ),
    ]
