# Generated by Django 4.2.4 on 2024-07-08 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_arrendador_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "rut",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=30)),
                ("adress", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tipo_usuario",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="tipo_usuario",
        ),
        migrations.RemoveField(
            model_name="inmueble",
            name="arrendador",
        ),
        migrations.AddField(
            model_name="inmueble",
            name="foto_portada",
            field=models.ImageField(
                default="inmuebles/casa1.jpg", upload_to="inmuebles"
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="arrendatario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Arrendador",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
