# Generated by Django 4.2.7 on 2024-07-11 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_cliente_remove_user_tipo_usuario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inmueble",
            name="arrendador",
            field=models.ForeignKey(
                blank=True,
                default="1",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="arrendatario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.cliente",
            ),
        ),
    ]
