# Generated by Django 4.2.7 on 2024-07-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_inmueble_arrendador_alter_inmueble_arrendatario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="tipo_usuario",
            field=models.ForeignKey(
                default="arrendador",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tipo_usuario",
            ),
        ),
    ]
